apiVersion: v1
kind: ServiceAccount
metadata:
 name: podsweeper
 namespace: processing

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podsweeper
  namespace: processing
  labels:
    app: dea-podsweeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dea-podsweeper
  template:
    metadata:
      labels:
        app: dea-podsweeper
    spec:
      serviceAccountName: podsweeper
      containers:
      - name: podsweeper
        image: uchchwhash/podsweeper:latest
        imagePullPolicy: Always
        command: ['python', '-m', 'podsweeper',
                  '--namespace', 'processing', '--expire-in-hours', '24', '--field-selector', 'status.phase=Pending']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: processing
  name: podsweeper
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podsweeper
  namespace: processing
roleRef:
  kind: Role
  name: podsweeper
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: podsweeper
  namespace: processing
